#!/usr/bin/env python3
"""The obscurity machinery must be term-driven without moving a single score.

The formula was lifted out of afl/build_db.py into obscurity.py so the NBA build
could score its players without copying it or inheriting AFL column names.
That refactor touches every stored AFL score, so the first test here is a
byte-identity check against a golden frame generated by the *pre-refactor*
implementation (tests/fixtures/obscurity_afl_golden.csv, produced once and
never regenerated -- regenerating it would defeat the point).

The rest pin the properties the generalisation has to preserve:

  * component columns appear in the model's declaration order;
  * a NaN drops its term and renormalises the rest, for EVERY term and not
    only the ones flagged `optional` -- the NBA needs exactly this for
    minutes, which are not recorded before 1951-52, and it is the easiest
    behaviour in the module to "fix" into a regression;
  * the two models carry different version numbers, because scores from
    different formulas are not comparable and a shared version would claim
    they are.

tests/test_obscurity.py is the AFL contract and must keep passing
unmodified. If it ever needs editing, this refactor is wrong.
"""

# --- test bootstrap: run from the repository root, import project modules ---
import os as _os
import sys as _sys

_ROOT = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
if _ROOT not in _sys.path:
    _sys.path.insert(0, _ROOT)
_os.chdir(_ROOT)
# --- end test bootstrap ---


import numpy as np
import pandas as pd
import pytest

from afl import build_db
import obscurity

GOLDEN = _os.path.join(_ROOT, "tests", "fixtures", "obscurity_afl_golden.csv")

OUTPUT_COLUMNS = ("obscurity", "obscurity_confidence", "obscurity_model")


def golden():
    return pd.read_csv(GOLDEN)


# ------------------------------------------------- the byte-identity gate

def test_afl_components_are_identical_to_the_pre_refactor_implementation():
    """Every column, every value. Not "close enough" -- identical.

    obscurity_confidence is a Python sum() over per-term Series, so a change
    in term iteration order can move it in the third decimal and the score
    in the first. Stored scores and every star rating derived from them
    would shift silently, so this is an equality check by design.
    """
    g = golden()
    expected = [c for c in g.columns
                if c.endswith("_component") or c in OUTPUT_COLUMNS]
    inputs = [c for c in g.columns if c not in expected]

    out = obscurity.components(g[inputs], obscurity.AFL_MODEL)

    assert list(out.columns) == expected
    for column in expected:
        pd.testing.assert_series_equal(
            out[column], g[column].astype(out[column].dtype),
            check_names=False,
            obj=f"{column} moved -- the refactor is not value-preserving")


def test_build_db_still_exposes_the_names_its_callers_import():
    """recompute_obscurity.py and test_obscurity.py both import from here."""
    assert build_db.OBSCURITY_MODEL_VERSION == obscurity.AFL_MODEL.version
    assert build_db.OBSCURITY_WEIGHTS == obscurity.AFL_MODEL.weights
    assert build_db.OBSCURITY_OPTIONAL_TERMS == ("brownlow",)
    assert callable(build_db.obscurity_components)
    assert callable(build_db.obscurity_score)


# ------------------------------------------------------- model invariants

@pytest.mark.parametrize("model", [obscurity.AFL_MODEL, obscurity.NBA_MODEL],
                         ids=["afl", "nba"])
def test_weights_sum_to_one(model):
    assert round(sum(model.weights.values()), 6) == 1.0


@pytest.mark.parametrize("model", [obscurity.AFL_MODEL, obscurity.NBA_MODEL],
                         ids=["afl", "nba"])
def test_term_names_are_unique(model):
    names = [t.name for t in model.terms]
    assert len(names) == len(set(names))


def test_the_two_models_are_versioned_apart():
    """A shared version number would claim the scores are comparable."""
    assert obscurity.NBA_MODEL.version == 1
    assert obscurity.AFL_MODEL.version == 2
    assert obscurity.NBA_MODEL.version != obscurity.AFL_MODEL.version


def test_required_columns_names_exactly_what_components_reads():
    """recompute_obscurity selects these, so a missing name scores on NaN."""
    assert obscurity.AFL_MODEL.required_columns() == [
        "career_games", "debut_season", "final_season",
        "career_goals", "finals_played", "career_brownlow"]
    assert obscurity.NBA_MODEL.required_columns() == [
        "career_games", "debut_season", "final_season", "career_minutes",
        "playoffs_played", "career_points", "n_clubs"]


def test_required_columns_includes_the_columns_a_derivation_reads():
    """span reads two columns and names neither -- they must still appear."""
    for model in (obscurity.AFL_MODEL, obscurity.NBA_MODEL):
        assert "debut_season" in model.required_columns()
        assert "final_season" in model.required_columns()


# -------------------------------------------------------- component shape

def nba_frame(rows):
    """rows: (games, minutes, playoffs, points, teams, debut, final)."""
    return pd.DataFrame(rows, columns=[
        "career_games", "career_minutes", "playoffs_played",
        "career_points", "n_clubs", "debut_season", "final_season"])


def test_every_term_produces_a_component_column_in_declaration_order():
    out = obscurity.components(
        nba_frame([(500, 12000.0, 40, 8000, 2, 1990, 2004),
                   (12, 90.0, 0, 30, 1, 1998, 1998)]),
        obscurity.NBA_MODEL)
    assert list(out.columns) == [
        "games_component", "span_component", "minutes_component",
        "era_component", "playoffs_component", "points_component",
        "teams_component", *OUTPUT_COLUMNS]


def test_obscurity_model_column_records_the_models_version():
    out = obscurity.components(
        nba_frame([(500, 12000.0, 40, 8000, 2, 1990, 2004)]),
        obscurity.NBA_MODEL)
    assert out["obscurity_model"].iloc[0] == obscurity.NBA_MODEL.version


# --------------------------------------------------- missing is not zero

def test_a_missing_optional_term_drops_and_renormalises():
    """No minutes recorded is not "played no minutes"."""
    rows = [(200, np.nan, 5, 3000, 1, 1946, 1950),
            (200, 6000.0, 5, 3000, 1, 1946, 1950)]
    out = obscurity.components(nba_frame(rows), obscurity.NBA_MODEL)
    assert pd.isna(out["minutes_component"].iloc[0])
    # 1.0 minus the minutes weight, renormalised over what is left.
    assert out["obscurity_confidence"].iloc[0] == pytest.approx(0.85)
    assert out["obscurity_confidence"].iloc[1] == pytest.approx(1.0)


def test_a_missing_NON_optional_term_drops_by_the_same_path():
    """era is not flagged optional, but a NULL final_season still drops it.

    This is behaviour the pre-refactor code had by accident of computing
    `available` over every term rather than only the flagged ones, and
    tests/test_obscurity.py depends on it for the AFL. Pinning it here
    stops a future reader "tidying" the loop to consult `optional`.
    """
    rows = [(200, 6000.0, 5, 3000, 1, 1990, np.nan),
            (200, 6000.0, 5, 3000, 1, 1990, 2000)]
    out = obscurity.components(nba_frame(rows), obscurity.NBA_MODEL)
    assert pd.isna(out["era_component"].iloc[0])
    assert out["obscurity_confidence"].iloc[0] == pytest.approx(0.85)
    assert out["obscurity_confidence"].iloc[1] == pytest.approx(1.0)


def test_a_dropped_term_does_not_drag_the_score_toward_zero():
    """The renormalised score must sit where the remaining terms put it."""
    rows = [(1, np.nan, 0, 0, 1, 1946, 1946)]
    rows += [(400 + i, 20000.0, 60, 20000, 1, 1995, 2012) for i in range(20)]
    out = obscurity.components(nba_frame(rows), obscurity.NBA_MODEL)
    # A one-game career with no minutes data is still maximally obscure on
    # every term it does have, so dropping minutes must not pull it down.
    assert out["obscurity"].iloc[0] > 95, out["obscurity"].iloc[0]


# --------------------------------------------------------- the disclaimer

def test_the_disclaimer_names_the_models_own_terms():
    """The AFL string went stale claiming a term the formula never had."""
    import sports
    afl = obscurity.disclaimer(obscurity.AFL_MODEL, sports.AFL.vocab)
    assert "Brownlow votes" in afl
    assert "goals" in afl

    nba = obscurity.disclaimer(obscurity.NBA_MODEL, sports.NBA.vocab)
    assert "Brownlow" not in nba
    assert "goals" not in nba
    assert "minutes played" in nba
    assert "playoff games" in nba
    assert "teams" in nba          # {clubs} filled from the NBA vocab


def main():
    import subprocess
    return subprocess.call([_sys.executable, "-m", "pytest", __file__, "-q"])


if __name__ == "__main__":
    _sys.exit(main())
